# Generated by Django 2.2 on 2019-05-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_audio_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(null=True, upload_to='home/amin/Desktop/youtube project/youtubeService/staticfiles/media'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='originalurl',
            field=models.URLField(max_length=512, unique=True),
        ),
    ]
