# Generated by Django 2.2.3 on 2019-08-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190622_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(null=True, upload_to='home/amin/Desktop/git-files/local-youtube-project/staticfiles/media'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('_type', models.CharField(max_length=300)),
                ('list_id', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('uploader', models.CharField(max_length=300)),
                ('uploader_id', models.CharField(max_length=300)),
                ('uploader_url', models.CharField(max_length=300)),
                ('extractor', models.CharField(max_length=300)),
                ('webpage_url', models.CharField(max_length=300)),
                ('webpage_url_basename', models.CharField(max_length=300)),
                ('extractor_key', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('publications', models.ManyToManyField(related_name='video_videoList_manyToMany', to='main.Audio')),
            ],
            options={
                'ordering': ('create_date',),
            },
        ),
    ]
