# Generated by Django 2.2.3 on 2019-08-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190811_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolist',
            old_name='_type',
            new_name='list_type',
        ),
        migrations.RemoveField(
            model_name='videolist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videolist',
            name='publications',
        ),
        migrations.AddField(
            model_name='videolist',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='video_videoList_manyToMany', to='main.Audio'),
        ),
    ]
