# Generated by Django 2.2.3 on 2019-08-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190811_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolist',
            name='list_type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
