# Generated by Django 2.2.3 on 2019-08-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190811_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='extend',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
