# Generated by Django 2.2.1 on 2019-06-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190510_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='home/amin/Desktop/Desktop /youtube project/jjj/staticfiles/media/images/'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(null=True, upload_to='home/amin/Desktop/Desktop /youtube project/jjj/staticfiles/media'),
        ),
    ]
