# Generated by Django 2.2.1 on 2019-06-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190622_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='home/amin/Desktop/Desktop /youtube project/jjj/staticfiles/media/images/'),
        ),
    ]
